name: Create new repo

on:
  issue_comment:
    types: [created]

jobs:
  create-repo:
    name: Create new repo
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/create-org')

    steps:
      - name: Check out scripts
        uses: actions/checkout@v3

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Parse issue body
        id: parse-issue-body
        uses: actions/github-script@v5
        with:
          script: |
            require('./.github/scripts/parse-issue-body.js')({context, core})

      - run: echo ${{ steps.parse-issue-body.outputs.repo-name }}
